In [1]:
import numpy as np

# Q1 (a) Reverse array
arr = np.array([1, 2, 3, 6, 4, 5])
print("Reversed:", arr[::-1])


Reversed: [5 4 6 3 2 1]


In [2]:
# Q1 (b) Flatten array using two methods
array1 = np.array([[1, 2, 3], [2, 4, 5], [1, 2, 3]])
print("Flattened (ravel):", array1.ravel())
print("Flattened (flatten):", array1.flatten())

Flattened (ravel): [1 2 3 2 4 5 1 2 3]
Flattened (flatten): [1 2 3 2 4 5 1 2 3]


In [3]:
# Q1 (c) Compare arrays
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[1, 2], [3, 4]])
print("Are arrays equal:", np.array_equal(arr1, arr2))

Are arrays equal: True


In [4]:
# Q1 (d) Most frequent value and indices
def most_frequent(x):
    vals, counts = np.unique(x, return_counts=True)
    max_val = vals[np.argmax(counts)]
    indices = np.where(x == max_val)[0]
    return max_val, indices
x = np.array([1,2,3,4,5,1,2,1,1,1])
y = np.array([1,1,1,2,3,4,2,4,3,3])
print("Most frequent in x:", most_frequent(x))
print("Most frequent in y:", most_frequent(y))

Most frequent in x: (np.int64(1), array([0, 5, 7, 8, 9]))
Most frequent in y: (np.int64(1), array([0, 1, 2]))


In [5]:
# Q1 (e) Matrix operations
gfg = np.matrix('[4, 1, 9; 12, 3, 1; 4, 5, 6]')
print("Sum of all:", gfg.sum())
print("Row-wise sum:", np.sum(gfg, axis=1))
print("Col-wise sum:", np.sum(gfg, axis=0))

Sum of all: 45
Row-wise sum: [[14]
 [16]
 [15]]
Col-wise sum: [[20  9 16]]


In [6]:
# Q1 (f) Advanced matrix operations
n_array = np.array([[55, 25, 15],[30, 44, 2],[11, 45, 77]])
print("Diagonal sum:", np.trace(n_array))
print("Eigenvalues:", np.linalg.eigvals(n_array))
eigenvalues, eigenvectors = np.linalg.eig(n_array)
print("Eigenvectors:\n", eigenvectors)
print("Inverse:\n", np.linalg.inv(n_array))
print("Determinant:", np.linalg.det(n_array))

Diagonal sum: 176
Eigenvalues: [98.16835147 28.097044   49.73460452]
Eigenvectors:
 [[ 0.4574917   0.34637121 -0.15017693]
 [ 0.28447814 -0.72784061 -0.4852124 ]
 [ 0.84248058  0.59184038  0.8614034 ]]
Inverse:
 [[ 0.02404141 -0.00911212 -0.00444671]
 [-0.01667882  0.02966905  0.0024785 ]
 [ 0.00631287 -0.01603732  0.01217379]]
Determinant: 137180.0000000001


In [7]:
# Q1 (g) Matrix multiplication and covariance
p1 = np.array([[1, 2], [2, 3]])
q1 = np.array([[4, 5], [6, 7]])
print("Product 1:\n", np.dot(p1, q1))
print("Covariance 1:\n", np.cov(p1, rowvar=False))

p2 = np.array([[1, 2], [2, 3], [4, 5]])
q2 = np.array([[4, 5, 1], [6, 7, 2]])
print("Product 2:\n", np.dot(p2, q2))
print("Covariance 2:\n", np.cov(p2, rowvar=False))

Product 1:
 [[16 19]
 [26 31]]
Covariance 1:
 [[0.5 0.5]
 [0.5 0.5]]
Product 2:
 [[16 19  5]
 [26 31  8]
 [46 55 14]]
Covariance 2:
 [[2.33333333 2.33333333]
 [2.33333333 2.33333333]]


In [8]:
# Q1 (h) Inner, Outer, Cartesian products
x = np.array([[2, 3, 4], [3, 2, 9]])
y = np.array([[1, 5, 0], [5, 10, 3]])
print("Inner:\n", np.inner(x, y))
print("Outer:\n", np.outer(x.flatten(), y.flatten()))
from itertools import product
print("Cartesian:\n", np.array(list(product(x.flatten(), y.flatten()))))

Inner:
 [[17 52]
 [13 62]]
Outer:
 [[ 2 10  0 10 20  6]
 [ 3 15  0 15 30  9]
 [ 4 20  0 20 40 12]
 [ 3 15  0 15 30  9]
 [ 2 10  0 10 20  6]
 [ 9 45  0 45 90 27]]
Cartesian:
 [[ 2  1]
 [ 2  5]
 [ 2  0]
 [ 2  5]
 [ 2 10]
 [ 2  3]
 [ 3  1]
 [ 3  5]
 [ 3  0]
 [ 3  5]
 [ 3 10]
 [ 3  3]
 [ 4  1]
 [ 4  5]
 [ 4  0]
 [ 4  5]
 [ 4 10]
 [ 4  3]
 [ 3  1]
 [ 3  5]
 [ 3  0]
 [ 3  5]
 [ 3 10]
 [ 3  3]
 [ 2  1]
 [ 2  5]
 [ 2  0]
 [ 2  5]
 [ 2 10]
 [ 2  3]
 [ 9  1]
 [ 9  5]
 [ 9  0]
 [ 9  5]
 [ 9 10]
 [ 9  3]]


In [9]:
# Q2 (a) Math and stats
array = np.array([[1, -2, 3],[-4, 5, -6]])
print("Absolute:\n", np.abs(array))
flat = array.flatten()
print("Percentiles (flat):", np.percentile(flat, [25, 50, 75]))
print("Percentiles (cols):", np.percentile(array, [25, 50, 75], axis=0))
print("Percentiles (rows):", np.percentile(array, [25, 50, 75], axis=1))
print("Mean (flat):", np.mean(flat))
print("Median (flat):", np.median(flat))
print("Std Dev (flat):", np.std(flat))
print("Mean (col):", np.mean(array, axis=0))
print("Median (row):", np.median(array, axis=1))

# Q2 (b) Floor, ceil, trunc, round
a = np.array([-1.8, -1.6, -0.5, 0.5,1.6, 1.8, 3.0])
print("Floor:", np.floor(a))
print("Ceil:", np.ceil(a))
print("Trunc:", np.trunc(a))
print("Round:", np.round(a))


Absolute:
 [[1 2 3]
 [4 5 6]]
Percentiles (flat): [-3.5 -0.5  2.5]
Percentiles (cols): [[-2.75 -0.25 -3.75]
 [-1.5   1.5  -1.5 ]
 [-0.25  3.25  0.75]]
Percentiles (rows): [[-0.5 -5. ]
 [ 1.  -4. ]
 [ 2.   0.5]]
Mean (flat): -0.5
Median (flat): -0.5
Std Dev (flat): 3.8622100754188224
Mean (col): [-1.5  1.5 -1.5]
Median (row): [ 1. -4.]
Floor: [-2. -2. -1.  0.  1.  1.  3.]
Ceil: [-1. -1. -0.  1.  2.  2.  3.]
Trunc: [-1. -1. -0.  0.  1.  1.  3.]
Round: [-2. -2. -0.  0.  2.  2.  3.]


In [10]:
# Q3 (a) Sorting
array = np.array([10, 52, 62, 16, 16, 54, 453])
print("Sorted:", np.sort(array))
print("Sorted indices:", np.argsort(array))
print("4 smallest:", np.sort(array)[:4])
print("5 largest:", np.sort(array)[-5:][::-1])

Sorted: [ 10  16  16  52  54  62 453]
Sorted indices: [0 3 4 1 5 2 6]
4 smallest: [10 16 16 52]
5 largest: [453  62  54  52  16]


In [11]:
# Q3 (b) Integer and float elements
array = np.array([1.0, 1.2, 2.2, 2.0, 3.0, 2.0])
ints = array[array == array.astype(int)]
floats = array[array != array.astype(int)]
print("Integers:", ints)
print("Floats:", floats)

Integers: [1. 2. 3. 2.]
Floats: [1.2 2.2]


In [16]:
from PIL import Image
import numpy as np

def img_to_array(path):
    img = Image.open(path)
    arr = np.array(img)
    if len(arr.shape) == 2:
        np.savetxt("grayscale_image.txt", arr, fmt='%d')
        print(f"{path} is a Grayscale image. Saved as 'grayscale_image.txt'")
    else:
        reshaped = arr.reshape(-1, arr.shape[-1])
        np.savetxt("rgb_image.txt", reshaped, fmt='%d')
        print(f"{path} is an RGB image. Saved as 'rgb_image.txt'")

img_to_array("gray_image.jpg")
img_to_array("color_image.jpg")

print("\n--- Loaded from grayscale_image.txt ---")
gray = np.loadtxt("grayscale_image.txt", dtype=int)
print(gray)

print("\n--- Loaded from rgb_image.txt ---")
rgb = np.loadtxt("rgb_image.txt", dtype=int).reshape(-1, 3)
print(rgb)

gray_image.jpg is a Grayscale image. Saved as 'grayscale_image.txt'
color_image.jpg is an RGB image. Saved as 'rgb_image.txt'

--- Loaded from grayscale_image.txt ---
[[ 0  0  0 ... 48 48 49]
 [ 0  0  0 ... 48 49 49]
 [ 0  0  1 ... 49 49 50]
 ...
 [48 48 49 ... 96 97 97]
 [48 49 49 ... 97 97 97]
 [49 49 50 ... 97 97 98]]

--- Loaded from rgb_image.txt ---
[[  1   1   1]
 [  1   1   1]
 [  3   1   2]
 ...
 [193 197 196]
 [196 198 197]
 [197 199 198]]
